Aqua: '#008db5'
Black: '#0e0e0e'
Charcoal: '#36454f'
Irish Green: '#00AC61'
Leaf: '#5c9346'
Natural: '#fff6ea' 
Navy: '#0f1830'
Olive: '#5b642f'
Sandstone: '#d4bf8e'
Sapphire: '#007AB3'
Tropical Blue: '#00A0B3'
True Royal: '#536ba7'
White: '#ffffff'
