const countries = [
  {"country": "Australia", "code": "AU", "locale": "en-AU", "currency": "AUD", "symbol": "$"},
  {"country": "Austria", "code": "AT", "locale": "de-AT", "currency": "EUR", "symbol": "€"},
  {"country": "Belgium", "code": "BE", "locale": "nl-BE", "currency": "EUR", "symbol": "€"},
  {"country": "Bulgaria", "code": "BG", "locale": "bg-BG", "currency": "BGN", "symbol": "лв"},
  {"country": "Canada", "code": "CA", "locale": "en-CA", "currency": "CAD", "symbol": "$"},
  {"country": "Croatia", "code": "HR", "locale": "hr-HR", "currency": "EUR", "symbol": "€"},
  {"country": "Cyprus", "code": "CY", "locale": "el-CY", "currency": "EUR", "symbol": "€"},
  {"country": "Czechia", "code": "CZ", "locale": "cs-CZ", "currency": "CZK", "symbol": "Kč"},
  {"country": "Denmark", "code": "DK", "locale": "da-DK", "currency": "DKK", "symbol": "kr"},
  {"country": "Estonia", "code": "EE", "locale": "et-EE", "currency": "EUR", "symbol": "€"},
  {"country": "Finland", "code": "FI", "locale": "fi-FI", "currency": "EUR", "symbol": "€"},
  {"country": "France", "code": "FR", "locale": "fr-FR", "currency": "EUR", "symbol": "€"},
  {"country": "Germany", "code": "DE", "locale": "de-DE", "currency": "EUR", "symbol": "€"},
  {"country": "Greece", "code": "GR", "locale": "el-GR", "currency": "EUR", "symbol": "€"},
  {"country": "Hong Kong SAR", "code": "HK", "locale": "zh-HK", "currency": "HKD", "symbol": "$"},
  {"country": "Hungary", "code": "HU", "locale": "hu-HU", "currency": "HUF", "symbol": "Ft"},
  {"country": "Ireland", "code": "IE", "locale": "en-IE", "currency": "EUR", "symbol": "€"},
  {"country": "Israel", "code": "IL", "locale": "he-IL", "currency": "ILS", "symbol": "₪"},
  {"country": "Italy", "code": "IT", "locale": "it-IT", "currency": "EUR", "symbol": "€"},
  {"country": "Japan", "code": "JP", "locale": "ja-JP", "currency": "JPY", "symbol": "¥"},
  {"country": "Latvia", "code": "LV", "locale": "lv-LV", "currency": "EUR", "symbol": "€"},
  {"country": "Lithuania", "code": "LT", "locale": "lt-LT", "currency": "EUR", "symbol": "€"},
  {"country": "Luxembourg", "code": "LU", "locale": "lb-LU", "currency": "EUR", "symbol": "€"},
  {"country": "Malaysia", "code": "MY", "locale": "ms-MY", "currency": "MYR", "symbol": "RM"},
  {"country": "Malta", "code": "MT", "locale": "mt-MT", "currency": "EUR", "symbol": "€"},
  {"country": "Netherlands", "code": "NL", "locale": "nl-NL", "currency": "EUR", "symbol": "€"},
  {"country": "New Zealand", "code": "NZ", "locale": "en-NZ", "currency": "NZD", "symbol": "$"},
  {"country": "Norway", "code": "NO", "locale": "nb-NO", "currency": "NOK", "symbol": "kr"},
  {"country": "Poland", "code": "PL", "locale": "pl-PL", "currency": "PLN", "symbol": "zł"},
  {"country": "Portugal", "code": "PT", "locale": "pt-PT", "currency": "EUR", "symbol": "€"},
  {"country": "Romania", "code": "RO", "locale": "ro-RO", "currency": "RON", "symbol": "Lei"},
  {"country": "Singapore", "code": "SG", "locale": "en-SG", "currency": "SGD", "symbol": "$"},
  {"country": "Slovakia", "code": "SK", "locale": "sk-SK", "currency": "EUR", "symbol": "€"},
  {"country": "Slovenia", "code": "SI", "locale": "sl-SI", "currency": "EUR", "symbol": "€"},
  {"country": "South Korea", "code": "KR", "locale": "ko-KR", "currency": "KRW", "symbol": "₩"},
  {"country": "Spain", "code": "ES", "locale": "es-ES", "currency": "EUR", "symbol": "€"},
  {"country": "Sweden", "code": "SE", "locale": "sv-SE", "currency": "SEK", "symbol": "kr"},
  {"country": "Switzerland", "code": "CH", "locale": "de-CH", "currency": "CHF", "symbol": "CHF"},
  {"country": "United Arab Emirates", "code": "AE", "locale": "ar-AE", "currency": "AED", "symbol": "د.إ"},
  {"country": "United Kingdom", "code": "GB", "locale": "en-GB", "currency": "GBP", "symbol": "£"},
  {"country": "United States", "code": "US", "locale": "en-US", "currency": "USD", "symbol": "$"}
];

export default countries;
